# http://localhost:8080/q/dev-ui/configuration-form-editor
%dev.quarkus.console.enabled=false
quarkus.langchain4j.timeout=3000s
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

# choix du provider
quarkus.langchain4j.chat-model.provider=ollama
#quarkus.langchain4j.chat-model.provider=ai-gemini

# ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434
#quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:0.5b
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:3b
quarkus.langchain4j.ollama.timeout=2M

# google gemini
quarkus.langchain4j.ai.gemini.api-key=${GOOGLE_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash